### ISSUE TITLE
issue : stopped at first screen

### ISSUE THREAD

**Issue by lioncho** [Rezaad94/tiktok#2]

**Comment by lioncho** [comment]
# Test

## Testing Video 
https://youtu.be/4CW455_ltJE

## Testing Memo
1. Result 
 now bot stopped "swipe up for more"
-> check log
From python
  File "C:\Users\chowi\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


From Appium
not found element

[W3C] Matched W3C error code 'no such element' to NoSuchElementError
[W3C (7dd8cd92)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[W3C (7dd8cd92)]     at AndroidUiautomator2Driver.findElOrEls (C:\Users\chowi\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\commands\find.js:75:11)
[W3C (7dd8cd92)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[HTTP] <-- POST /wd/hub/session/7dd8cd92-fe48-4dd2-8097-ced4bb814108/element 404

-> check tiktok version
17.6.41

-> check code 
last commit code is oct 3

-> i checked repo.
last commit code is oct 3

**Comment by lioncho** [comment]
Opinion: your last code was not updated.

**Comment by lioncho** [comment]
i made testing video
https://youtu.be/Aa_I_-ytq6A

**Comment by Rezaad94** [comment]
please check again, i change logic in sign in area

**Comment by lioncho** [comment]
I made testing video.
bot stopped at first swipe screen.
https://youtu.be/j_zmpdcQA9g
